name: GillesPy2 Test Coverage

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
      
    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install python-libsbml
        pip install cython
        pip install coverage
        
    - name: Run test suite
      run: coverage run --source=gillespy2 --omit=gillespy2/solvers/stochkit/* test/run_tests.py -m develop
